# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Mouse Connectomes # The title of the book. Will be placed in the left navbar.
author: Jaewon Chung, Eric B. Bridgeford # The author of the book
copyright: "2022" # Copyright year to be placed in the footer
logo: ./images/nd_logo.png # A path to the book logo

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: badea-mouse.tex
    theme: howto

sphinx:
  config:
    language: en
    bibtex_reference_style: author_year

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/neurodata/badea-mouse
  path_to_book: badea-mouse
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: ./images/nd_logo_small.png
  comments:
    hypothesis: true
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: false
  home_page_in_navbar: true

parse:
  myst_enable_extensions: #https://myst-parser.readthedocs.io/en/latest/sphinx/reference.html#sphinx-config-options
    - linkify # automatically identify “bare” web URLs and add hyperlinks
    - dollarmath
  myst_nb_output_stderr:
    - "remove"
